# Generated by Django 3.2.10 on 2022-01-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_movie_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celcius',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.FloatField(max_length=100)),
                ('temeperature', models.FloatField(max_length=100)),
                ('oventemperature', models.IntegerField()),
            ],
        ),
    ]
